#
# RUN FROM WITHIN "Vivado Tcl Shell" WITH COMMAND:
# source vivado_build_captain_75T.tcl -notrace
#
# Build for Captain 75T board (uses pcileech_enigma_x1 project generated by
# "generate – captain - 75T.bat" / vivado_generate_project_captain_75T.tcl).
#
puts "-------------------------------------------------------"
puts " STARTING SYNTHESIS STEP.                              "
puts "-------------------------------------------------------"
launch_runs -jobs 6 synth_1
puts "-------------------------------------------------------"
puts " WAITING FOR SYNTHESIS STEP TO FINISH ...              "
puts " THIS IS LIKELY TO TAKE A VERY LONG TIME.              "
puts "-------------------------------------------------------"
wait_on_run synth_1
puts "-------------------------------------------------------"
puts " STARTING IMPLEMENTATION STEP.                         "
puts "-------------------------------------------------------"
launch_runs -jobs 4 impl_1 -to_step write_bitstream
puts "-------------------------------------------------------"
puts " WAITING FOR IMPLEMENTATION STEP TO FINISH ...         "
puts " THIS IS LIKELY TO TAKE A VERY LONG TIME.              "
puts "-------------------------------------------------------"
wait_on_run impl_1
file copy -force ./pcileech_enigma_x1/pcileech_enigma_x1.runs/impl_1/pcileech_enigma_x1_top.bin pcileech_captain_75T.bin
puts "-------------------------------------------------------"
puts " BUILD HOPEFULLY COMPLETED.  -> pcileech_captain_75T.bin"
puts "-------------------------------------------------------"
